site_name: CookBake 
nav:
  - Home: index.md
  - Cook:
    - Casserole:
      - Seafood Lasagna: cook/casserole/seafood-lasagna.md
  - Bake: 
    - Breads: 
      - Sourdough: bake/breads/sourdough.md
      - Bread in One Hour: bake/breads/bread-in-one-hour.md
theme: lux 
